from crewai import Crew

from tasks.executive_task import build_executive_task
from agents.executive_agent import executive_agent


def run_executive_node(state):
    """
    Executive node for the VET/VTO workforce forecasting project.

    This node reads the current OperationalState after the forecast,
    staffing, and cost nodes have already run. It generates a business-facing
    executive summary and stores it in state.executive_summary.

    It does not change forecasts, staffing decisions, or cost calculations.
    """

    try:
        executive_task = build_executive_task(state)

        executive_crew = Crew(
            agents=[executive_agent],
            tasks=[executive_task],
            verbose=True
        )

        executive_result = executive_crew.kickoff()

        state.executive_summary = str(executive_result)

    except Exception as e:
        state.executive_summary = (
            "Executive summary could not be generated by the AI agent. "
            "The forecast, staffing recommendations, and cost analysis were still completed. "
            f"Technical error: {str(e)}"
        )

    return state